// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.message.proto

#include "chat.message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_chat_2emessage_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_chat_2emessage_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Message;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_chat_2emessage_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_UnreceivedMessage;
}  // namespace protobuf_chat_2emessage_2eproto
namespace ChatPb {
class MessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Message>
      _instance;
} _Message_default_instance_;
class MsgAckDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MsgAck>
      _instance;
} _MsgAck_default_instance_;
class UnreceivedMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UnreceivedMessage>
      _instance;
} _UnreceivedMessage_default_instance_;
class openReceivedMessageREQDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<openReceivedMessageREQ>
      _instance;
} _openReceivedMessageREQ_default_instance_;
class UnreceivedMessageRESDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<UnreceivedMessageRES>
      _instance;
} _UnreceivedMessageRES_default_instance_;
}  // namespace ChatPb
namespace protobuf_chat_2emessage_2eproto {
static void InitDefaultsMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ChatPb::_Message_default_instance_;
    new (ptr) ::ChatPb::Message();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ChatPb::Message::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Message =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMessage}, {}};

static void InitDefaultsMsgAck() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ChatPb::_MsgAck_default_instance_;
    new (ptr) ::ChatPb::MsgAck();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ChatPb::MsgAck::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_MsgAck =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMsgAck}, {}};

static void InitDefaultsUnreceivedMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ChatPb::_UnreceivedMessage_default_instance_;
    new (ptr) ::ChatPb::UnreceivedMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ChatPb::UnreceivedMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_UnreceivedMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsUnreceivedMessage}, {
      &protobuf_chat_2emessage_2eproto::scc_info_Message.base,}};

static void InitDefaultsopenReceivedMessageREQ() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ChatPb::_openReceivedMessageREQ_default_instance_;
    new (ptr) ::ChatPb::openReceivedMessageREQ();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ChatPb::openReceivedMessageREQ::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_openReceivedMessageREQ =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsopenReceivedMessageREQ}, {}};

static void InitDefaultsUnreceivedMessageRES() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ChatPb::_UnreceivedMessageRES_default_instance_;
    new (ptr) ::ChatPb::UnreceivedMessageRES();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ChatPb::UnreceivedMessageRES::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_UnreceivedMessageRES =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsUnreceivedMessageRES}, {
      &protobuf_chat_2emessage_2eproto::scc_info_UnreceivedMessage.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Message.base);
  ::google::protobuf::internal::InitSCC(&scc_info_MsgAck.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UnreceivedMessage.base);
  ::google::protobuf::internal::InitSCC(&scc_info_openReceivedMessageREQ.base);
  ::google::protobuf::internal::InitSCC(&scc_info_UnreceivedMessageRES.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::Message, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::Message, chatid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::Message, fromuserid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::Message, messageid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::Message, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::Message, localid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::MsgAck, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::MsgAck, chatid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::MsgAck, fromuserid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::UnreceivedMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::UnreceivedMessage, count_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::UnreceivedMessage, msgs_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::openReceivedMessageREQ, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::openReceivedMessageREQ, on_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::UnreceivedMessageRES, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::UnreceivedMessageRES, unreceivedmessages_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ChatPb::Message)},
  { 10, -1, sizeof(::ChatPb::MsgAck)},
  { 17, -1, sizeof(::ChatPb::UnreceivedMessage)},
  { 24, -1, sizeof(::ChatPb::openReceivedMessageREQ)},
  { 30, -1, sizeof(::ChatPb::UnreceivedMessageRES)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ChatPb::_Message_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ChatPb::_MsgAck_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ChatPb::_UnreceivedMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ChatPb::_openReceivedMessageREQ_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ChatPb::_UnreceivedMessageRES_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "chat.message.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022chat.message.proto\022\006ChatPb\"b\n\007Message\022"
      "\016\n\006chatId\030\001 \001(\t\022\022\n\nfromUserId\030\002 \001(\t\022\021\n\tm"
      "essageId\030\003 \001(\t\022\017\n\007message\030\004 \001(\t\022\017\n\007local"
      "Id\030\005 \001(\t\",\n\006MsgAck\022\016\n\006chatId\030\001 \001(\t\022\022\n\nfr"
      "omUserId\030\002 \001(\t\"A\n\021UnreceivedMessage\022\r\n\005c"
      "ount\030\001 \001(\005\022\035\n\004msgs\030\002 \003(\0132\017.ChatPb.Messag"
      "e\"$\n\026openReceivedMessageREQ\022\n\n\002on\030\001 \001(\010\""
      "M\n\024UnreceivedMessageRES\0225\n\022unreceivedMes"
      "sages\030\001 \003(\0132\031.ChatPb.UnreceivedMessageb\006"
      "proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 366);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "chat.message.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_chat_2emessage_2eproto
namespace ChatPb {

// ===================================================================

void Message::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Message::kChatIdFieldNumber;
const int Message::kFromUserIdFieldNumber;
const int Message::kMessageIdFieldNumber;
const int Message::kMessageFieldNumber;
const int Message::kLocalIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Message::Message()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_chat_2emessage_2eproto::scc_info_Message.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ChatPb.Message)
}
Message::Message(const Message& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  chatid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.chatid().size() > 0) {
    chatid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.chatid_);
  }
  fromuserid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.fromuserid().size() > 0) {
    fromuserid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fromuserid_);
  }
  messageid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.messageid().size() > 0) {
    messageid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messageid_);
  }
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  localid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.localid().size() > 0) {
    localid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.localid_);
  }
  // @@protoc_insertion_point(copy_constructor:ChatPb.Message)
}

void Message::SharedCtor() {
  chatid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fromuserid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messageid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  localid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Message::~Message() {
  // @@protoc_insertion_point(destructor:ChatPb.Message)
  SharedDtor();
}

void Message::SharedDtor() {
  chatid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fromuserid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messageid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  localid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Message::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Message::descriptor() {
  ::protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Message& Message::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_chat_2emessage_2eproto::scc_info_Message.base);
  return *internal_default_instance();
}


void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:ChatPb.Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  chatid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fromuserid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  messageid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  localid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Message::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ChatPb.Message)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string chatId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_chatid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->chatid().data(), static_cast<int>(this->chatid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.Message.chatId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string fromUserId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fromuserid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fromuserid().data(), static_cast<int>(this->fromuserid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.Message.fromUserId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string messageId = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_messageid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->messageid().data(), static_cast<int>(this->messageid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.Message.messageId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.Message.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string localId = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_localid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->localid().data(), static_cast<int>(this->localid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.Message.localId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ChatPb.Message)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ChatPb.Message)
  return false;
#undef DO_
}

void Message::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ChatPb.Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string chatId = 1;
  if (this->chatid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->chatid().data(), static_cast<int>(this->chatid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.chatId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->chatid(), output);
  }

  // string fromUserId = 2;
  if (this->fromuserid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fromuserid().data(), static_cast<int>(this->fromuserid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.fromUserId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->fromuserid(), output);
  }

  // string messageId = 3;
  if (this->messageid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messageid().data(), static_cast<int>(this->messageid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.messageId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->messageid(), output);
  }

  // string message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->message(), output);
  }

  // string localId = 5;
  if (this->localid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->localid().data(), static_cast<int>(this->localid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.localId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->localid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ChatPb.Message)
}

::google::protobuf::uint8* Message::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ChatPb.Message)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string chatId = 1;
  if (this->chatid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->chatid().data(), static_cast<int>(this->chatid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.chatId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->chatid(), target);
  }

  // string fromUserId = 2;
  if (this->fromuserid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fromuserid().data(), static_cast<int>(this->fromuserid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.fromUserId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->fromuserid(), target);
  }

  // string messageId = 3;
  if (this->messageid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->messageid().data(), static_cast<int>(this->messageid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.messageId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->messageid(), target);
  }

  // string message = 4;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->message(), target);
  }

  // string localId = 5;
  if (this->localid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->localid().data(), static_cast<int>(this->localid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.Message.localId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->localid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChatPb.Message)
  return target;
}

size_t Message::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChatPb.Message)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string chatId = 1;
  if (this->chatid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->chatid());
  }

  // string fromUserId = 2;
  if (this->fromuserid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fromuserid());
  }

  // string messageId = 3;
  if (this->messageid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->messageid());
  }

  // string message = 4;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // string localId = 5;
  if (this->localid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->localid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Message::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ChatPb.Message)
  GOOGLE_DCHECK_NE(&from, this);
  const Message* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Message>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ChatPb.Message)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ChatPb.Message)
    MergeFrom(*source);
  }
}

void Message::MergeFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ChatPb.Message)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.chatid().size() > 0) {

    chatid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.chatid_);
  }
  if (from.fromuserid().size() > 0) {

    fromuserid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fromuserid_);
  }
  if (from.messageid().size() > 0) {

    messageid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.messageid_);
  }
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.localid().size() > 0) {

    localid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.localid_);
  }
}

void Message::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ChatPb.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChatPb.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message::IsInitialized() const {
  return true;
}

void Message::Swap(Message* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Message::InternalSwap(Message* other) {
  using std::swap;
  chatid_.Swap(&other->chatid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  fromuserid_.Swap(&other->fromuserid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  messageid_.Swap(&other->messageid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  localid_.Swap(&other->localid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Message::GetMetadata() const {
  protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MsgAck::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MsgAck::kChatIdFieldNumber;
const int MsgAck::kFromUserIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MsgAck::MsgAck()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_chat_2emessage_2eproto::scc_info_MsgAck.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ChatPb.MsgAck)
}
MsgAck::MsgAck(const MsgAck& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  chatid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.chatid().size() > 0) {
    chatid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.chatid_);
  }
  fromuserid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.fromuserid().size() > 0) {
    fromuserid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fromuserid_);
  }
  // @@protoc_insertion_point(copy_constructor:ChatPb.MsgAck)
}

void MsgAck::SharedCtor() {
  chatid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fromuserid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

MsgAck::~MsgAck() {
  // @@protoc_insertion_point(destructor:ChatPb.MsgAck)
  SharedDtor();
}

void MsgAck::SharedDtor() {
  chatid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fromuserid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MsgAck::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MsgAck::descriptor() {
  ::protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MsgAck& MsgAck::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_chat_2emessage_2eproto::scc_info_MsgAck.base);
  return *internal_default_instance();
}


void MsgAck::Clear() {
// @@protoc_insertion_point(message_clear_start:ChatPb.MsgAck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  chatid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fromuserid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool MsgAck::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ChatPb.MsgAck)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string chatId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_chatid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->chatid().data(), static_cast<int>(this->chatid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.MsgAck.chatId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string fromUserId = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fromuserid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fromuserid().data(), static_cast<int>(this->fromuserid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.MsgAck.fromUserId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ChatPb.MsgAck)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ChatPb.MsgAck)
  return false;
#undef DO_
}

void MsgAck::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ChatPb.MsgAck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string chatId = 1;
  if (this->chatid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->chatid().data(), static_cast<int>(this->chatid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.MsgAck.chatId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->chatid(), output);
  }

  // string fromUserId = 2;
  if (this->fromuserid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fromuserid().data(), static_cast<int>(this->fromuserid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.MsgAck.fromUserId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->fromuserid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ChatPb.MsgAck)
}

::google::protobuf::uint8* MsgAck::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ChatPb.MsgAck)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string chatId = 1;
  if (this->chatid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->chatid().data(), static_cast<int>(this->chatid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.MsgAck.chatId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->chatid(), target);
  }

  // string fromUserId = 2;
  if (this->fromuserid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fromuserid().data(), static_cast<int>(this->fromuserid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.MsgAck.fromUserId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->fromuserid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChatPb.MsgAck)
  return target;
}

size_t MsgAck::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChatPb.MsgAck)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string chatId = 1;
  if (this->chatid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->chatid());
  }

  // string fromUserId = 2;
  if (this->fromuserid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fromuserid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MsgAck::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ChatPb.MsgAck)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgAck* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MsgAck>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ChatPb.MsgAck)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ChatPb.MsgAck)
    MergeFrom(*source);
  }
}

void MsgAck::MergeFrom(const MsgAck& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ChatPb.MsgAck)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.chatid().size() > 0) {

    chatid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.chatid_);
  }
  if (from.fromuserid().size() > 0) {

    fromuserid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fromuserid_);
  }
}

void MsgAck::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ChatPb.MsgAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgAck::CopyFrom(const MsgAck& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChatPb.MsgAck)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgAck::IsInitialized() const {
  return true;
}

void MsgAck::Swap(MsgAck* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MsgAck::InternalSwap(MsgAck* other) {
  using std::swap;
  chatid_.Swap(&other->chatid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  fromuserid_.Swap(&other->fromuserid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MsgAck::GetMetadata() const {
  protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UnreceivedMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UnreceivedMessage::kCountFieldNumber;
const int UnreceivedMessage::kMsgsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UnreceivedMessage::UnreceivedMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_chat_2emessage_2eproto::scc_info_UnreceivedMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ChatPb.UnreceivedMessage)
}
UnreceivedMessage::UnreceivedMessage(const UnreceivedMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      msgs_(from.msgs_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  count_ = from.count_;
  // @@protoc_insertion_point(copy_constructor:ChatPb.UnreceivedMessage)
}

void UnreceivedMessage::SharedCtor() {
  count_ = 0;
}

UnreceivedMessage::~UnreceivedMessage() {
  // @@protoc_insertion_point(destructor:ChatPb.UnreceivedMessage)
  SharedDtor();
}

void UnreceivedMessage::SharedDtor() {
}

void UnreceivedMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UnreceivedMessage::descriptor() {
  ::protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UnreceivedMessage& UnreceivedMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_chat_2emessage_2eproto::scc_info_UnreceivedMessage.base);
  return *internal_default_instance();
}


void UnreceivedMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:ChatPb.UnreceivedMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msgs_.Clear();
  count_ = 0;
  _internal_metadata_.Clear();
}

bool UnreceivedMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ChatPb.UnreceivedMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 count = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &count_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ChatPb.Message msgs = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_msgs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ChatPb.UnreceivedMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ChatPb.UnreceivedMessage)
  return false;
#undef DO_
}

void UnreceivedMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ChatPb.UnreceivedMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 count = 1;
  if (this->count() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->count(), output);
  }

  // repeated .ChatPb.Message msgs = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->msgs_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->msgs(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ChatPb.UnreceivedMessage)
}

::google::protobuf::uint8* UnreceivedMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ChatPb.UnreceivedMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 count = 1;
  if (this->count() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->count(), target);
  }

  // repeated .ChatPb.Message msgs = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->msgs_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->msgs(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChatPb.UnreceivedMessage)
  return target;
}

size_t UnreceivedMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChatPb.UnreceivedMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .ChatPb.Message msgs = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->msgs_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->msgs(static_cast<int>(i)));
    }
  }

  // int32 count = 1;
  if (this->count() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->count());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UnreceivedMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ChatPb.UnreceivedMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const UnreceivedMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UnreceivedMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ChatPb.UnreceivedMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ChatPb.UnreceivedMessage)
    MergeFrom(*source);
  }
}

void UnreceivedMessage::MergeFrom(const UnreceivedMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ChatPb.UnreceivedMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  msgs_.MergeFrom(from.msgs_);
  if (from.count() != 0) {
    set_count(from.count());
  }
}

void UnreceivedMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ChatPb.UnreceivedMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UnreceivedMessage::CopyFrom(const UnreceivedMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChatPb.UnreceivedMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnreceivedMessage::IsInitialized() const {
  return true;
}

void UnreceivedMessage::Swap(UnreceivedMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UnreceivedMessage::InternalSwap(UnreceivedMessage* other) {
  using std::swap;
  CastToBase(&msgs_)->InternalSwap(CastToBase(&other->msgs_));
  swap(count_, other->count_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UnreceivedMessage::GetMetadata() const {
  protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void openReceivedMessageREQ::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int openReceivedMessageREQ::kOnFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

openReceivedMessageREQ::openReceivedMessageREQ()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_chat_2emessage_2eproto::scc_info_openReceivedMessageREQ.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ChatPb.openReceivedMessageREQ)
}
openReceivedMessageREQ::openReceivedMessageREQ(const openReceivedMessageREQ& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  on_ = from.on_;
  // @@protoc_insertion_point(copy_constructor:ChatPb.openReceivedMessageREQ)
}

void openReceivedMessageREQ::SharedCtor() {
  on_ = false;
}

openReceivedMessageREQ::~openReceivedMessageREQ() {
  // @@protoc_insertion_point(destructor:ChatPb.openReceivedMessageREQ)
  SharedDtor();
}

void openReceivedMessageREQ::SharedDtor() {
}

void openReceivedMessageREQ::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* openReceivedMessageREQ::descriptor() {
  ::protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const openReceivedMessageREQ& openReceivedMessageREQ::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_chat_2emessage_2eproto::scc_info_openReceivedMessageREQ.base);
  return *internal_default_instance();
}


void openReceivedMessageREQ::Clear() {
// @@protoc_insertion_point(message_clear_start:ChatPb.openReceivedMessageREQ)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  on_ = false;
  _internal_metadata_.Clear();
}

bool openReceivedMessageREQ::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ChatPb.openReceivedMessageREQ)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool on = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &on_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ChatPb.openReceivedMessageREQ)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ChatPb.openReceivedMessageREQ)
  return false;
#undef DO_
}

void openReceivedMessageREQ::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ChatPb.openReceivedMessageREQ)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool on = 1;
  if (this->on() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->on(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ChatPb.openReceivedMessageREQ)
}

::google::protobuf::uint8* openReceivedMessageREQ::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ChatPb.openReceivedMessageREQ)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool on = 1;
  if (this->on() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->on(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChatPb.openReceivedMessageREQ)
  return target;
}

size_t openReceivedMessageREQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChatPb.openReceivedMessageREQ)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bool on = 1;
  if (this->on() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void openReceivedMessageREQ::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ChatPb.openReceivedMessageREQ)
  GOOGLE_DCHECK_NE(&from, this);
  const openReceivedMessageREQ* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const openReceivedMessageREQ>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ChatPb.openReceivedMessageREQ)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ChatPb.openReceivedMessageREQ)
    MergeFrom(*source);
  }
}

void openReceivedMessageREQ::MergeFrom(const openReceivedMessageREQ& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ChatPb.openReceivedMessageREQ)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.on() != 0) {
    set_on(from.on());
  }
}

void openReceivedMessageREQ::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ChatPb.openReceivedMessageREQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void openReceivedMessageREQ::CopyFrom(const openReceivedMessageREQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChatPb.openReceivedMessageREQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool openReceivedMessageREQ::IsInitialized() const {
  return true;
}

void openReceivedMessageREQ::Swap(openReceivedMessageREQ* other) {
  if (other == this) return;
  InternalSwap(other);
}
void openReceivedMessageREQ::InternalSwap(openReceivedMessageREQ* other) {
  using std::swap;
  swap(on_, other->on_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata openReceivedMessageREQ::GetMetadata() const {
  protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void UnreceivedMessageRES::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int UnreceivedMessageRES::kUnreceivedMessagesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

UnreceivedMessageRES::UnreceivedMessageRES()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_chat_2emessage_2eproto::scc_info_UnreceivedMessageRES.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ChatPb.UnreceivedMessageRES)
}
UnreceivedMessageRES::UnreceivedMessageRES(const UnreceivedMessageRES& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      unreceivedmessages_(from.unreceivedmessages_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ChatPb.UnreceivedMessageRES)
}

void UnreceivedMessageRES::SharedCtor() {
}

UnreceivedMessageRES::~UnreceivedMessageRES() {
  // @@protoc_insertion_point(destructor:ChatPb.UnreceivedMessageRES)
  SharedDtor();
}

void UnreceivedMessageRES::SharedDtor() {
}

void UnreceivedMessageRES::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* UnreceivedMessageRES::descriptor() {
  ::protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const UnreceivedMessageRES& UnreceivedMessageRES::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_chat_2emessage_2eproto::scc_info_UnreceivedMessageRES.base);
  return *internal_default_instance();
}


void UnreceivedMessageRES::Clear() {
// @@protoc_insertion_point(message_clear_start:ChatPb.UnreceivedMessageRES)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  unreceivedmessages_.Clear();
  _internal_metadata_.Clear();
}

bool UnreceivedMessageRES::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ChatPb.UnreceivedMessageRES)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .ChatPb.UnreceivedMessage unreceivedMessages = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_unreceivedmessages()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ChatPb.UnreceivedMessageRES)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ChatPb.UnreceivedMessageRES)
  return false;
#undef DO_
}

void UnreceivedMessageRES::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ChatPb.UnreceivedMessageRES)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ChatPb.UnreceivedMessage unreceivedMessages = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->unreceivedmessages_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->unreceivedmessages(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ChatPb.UnreceivedMessageRES)
}

::google::protobuf::uint8* UnreceivedMessageRES::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ChatPb.UnreceivedMessageRES)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ChatPb.UnreceivedMessage unreceivedMessages = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->unreceivedmessages_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->unreceivedmessages(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChatPb.UnreceivedMessageRES)
  return target;
}

size_t UnreceivedMessageRES::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChatPb.UnreceivedMessageRES)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .ChatPb.UnreceivedMessage unreceivedMessages = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->unreceivedmessages_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->unreceivedmessages(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void UnreceivedMessageRES::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ChatPb.UnreceivedMessageRES)
  GOOGLE_DCHECK_NE(&from, this);
  const UnreceivedMessageRES* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const UnreceivedMessageRES>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ChatPb.UnreceivedMessageRES)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ChatPb.UnreceivedMessageRES)
    MergeFrom(*source);
  }
}

void UnreceivedMessageRES::MergeFrom(const UnreceivedMessageRES& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ChatPb.UnreceivedMessageRES)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  unreceivedmessages_.MergeFrom(from.unreceivedmessages_);
}

void UnreceivedMessageRES::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ChatPb.UnreceivedMessageRES)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void UnreceivedMessageRES::CopyFrom(const UnreceivedMessageRES& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChatPb.UnreceivedMessageRES)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool UnreceivedMessageRES::IsInitialized() const {
  return true;
}

void UnreceivedMessageRES::Swap(UnreceivedMessageRES* other) {
  if (other == this) return;
  InternalSwap(other);
}
void UnreceivedMessageRES::InternalSwap(UnreceivedMessageRES* other) {
  using std::swap;
  CastToBase(&unreceivedmessages_)->InternalSwap(CastToBase(&other->unreceivedmessages_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata UnreceivedMessageRES::GetMetadata() const {
  protobuf_chat_2emessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2emessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ChatPb
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ChatPb::Message* Arena::CreateMaybeMessage< ::ChatPb::Message >(Arena* arena) {
  return Arena::CreateInternal< ::ChatPb::Message >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ChatPb::MsgAck* Arena::CreateMaybeMessage< ::ChatPb::MsgAck >(Arena* arena) {
  return Arena::CreateInternal< ::ChatPb::MsgAck >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ChatPb::UnreceivedMessage* Arena::CreateMaybeMessage< ::ChatPb::UnreceivedMessage >(Arena* arena) {
  return Arena::CreateInternal< ::ChatPb::UnreceivedMessage >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ChatPb::openReceivedMessageREQ* Arena::CreateMaybeMessage< ::ChatPb::openReceivedMessageREQ >(Arena* arena) {
  return Arena::CreateInternal< ::ChatPb::openReceivedMessageREQ >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ChatPb::UnreceivedMessageRES* Arena::CreateMaybeMessage< ::ChatPb::UnreceivedMessageRES >(Arena* arena) {
  return Arena::CreateInternal< ::ChatPb::UnreceivedMessageRES >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
