// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.authenticate.proto

#include "chat.authenticate.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_chat_2euser_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_chat_2euser_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_User;
}  // namespace protobuf_chat_2euser_2eproto
namespace ChatPb {
class AuthenticateREQDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AuthenticateREQ>
      _instance;
} _AuthenticateREQ_default_instance_;
class AuthenticateRESDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AuthenticateRES>
      _instance;
} _AuthenticateRES_default_instance_;
}  // namespace ChatPb
namespace protobuf_chat_2eauthenticate_2eproto {
static void InitDefaultsAuthenticateREQ() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ChatPb::_AuthenticateREQ_default_instance_;
    new (ptr) ::ChatPb::AuthenticateREQ();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ChatPb::AuthenticateREQ::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AuthenticateREQ =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAuthenticateREQ}, {}};

static void InitDefaultsAuthenticateRES() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ChatPb::_AuthenticateRES_default_instance_;
    new (ptr) ::ChatPb::AuthenticateRES();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ChatPb::AuthenticateRES::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_AuthenticateRES =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsAuthenticateRES}, {
      &protobuf_chat_2euser_2eproto::scc_info_User.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_AuthenticateREQ.base);
  ::google::protobuf::internal::InitSCC(&scc_info_AuthenticateRES.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::AuthenticateREQ, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::AuthenticateREQ, openid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::AuthenticateREQ, accesstoken_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::AuthenticateREQ, appid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::AuthenticateRES, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::AuthenticateRES, authorized_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::AuthenticateRES, user_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::AuthenticateRES, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChatPb::AuthenticateRES, code_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ChatPb::AuthenticateREQ)},
  { 8, -1, sizeof(::ChatPb::AuthenticateRES)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ChatPb::_AuthenticateREQ_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ChatPb::_AuthenticateRES_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "chat.authenticate.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\027chat.authenticate.proto\022\006ChatPb\032\017chat."
      "base.proto\032\017chat.user.proto\"E\n\017Authentic"
      "ateREQ\022\016\n\006openId\030\001 \001(\t\022\023\n\013accessToken\030\002 "
      "\001(\t\022\r\n\005appId\030\003 \001(\t\"s\n\017AuthenticateRES\022\022\n"
      "\nauthorized\030\001 \001(\010\022\032\n\004user\030\002 \001(\0132\014.ChatPb"
      ".User\022\017\n\007message\030\003 \001(\t\022\037\n\004code\030\004 \001(\0162\021.C"
      "hatPb.ErrorCodeb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 263);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "chat.authenticate.proto", &protobuf_RegisterTypes);
  ::protobuf_chat_2ebase_2eproto::AddDescriptors();
  ::protobuf_chat_2euser_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_chat_2eauthenticate_2eproto
namespace ChatPb {

// ===================================================================

void AuthenticateREQ::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AuthenticateREQ::kOpenIdFieldNumber;
const int AuthenticateREQ::kAccessTokenFieldNumber;
const int AuthenticateREQ::kAppIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AuthenticateREQ::AuthenticateREQ()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_chat_2eauthenticate_2eproto::scc_info_AuthenticateREQ.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ChatPb.AuthenticateREQ)
}
AuthenticateREQ::AuthenticateREQ(const AuthenticateREQ& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  openid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.openid().size() > 0) {
    openid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.openid_);
  }
  accesstoken_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.accesstoken().size() > 0) {
    accesstoken_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accesstoken_);
  }
  appid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.appid().size() > 0) {
    appid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.appid_);
  }
  // @@protoc_insertion_point(copy_constructor:ChatPb.AuthenticateREQ)
}

void AuthenticateREQ::SharedCtor() {
  openid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  accesstoken_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  appid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

AuthenticateREQ::~AuthenticateREQ() {
  // @@protoc_insertion_point(destructor:ChatPb.AuthenticateREQ)
  SharedDtor();
}

void AuthenticateREQ::SharedDtor() {
  openid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  accesstoken_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  appid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void AuthenticateREQ::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AuthenticateREQ::descriptor() {
  ::protobuf_chat_2eauthenticate_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2eauthenticate_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AuthenticateREQ& AuthenticateREQ::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_chat_2eauthenticate_2eproto::scc_info_AuthenticateREQ.base);
  return *internal_default_instance();
}


void AuthenticateREQ::Clear() {
// @@protoc_insertion_point(message_clear_start:ChatPb.AuthenticateREQ)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  openid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  accesstoken_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  appid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool AuthenticateREQ::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ChatPb.AuthenticateREQ)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string openId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_openid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->openid().data(), static_cast<int>(this->openid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.AuthenticateREQ.openId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string accessToken = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_accesstoken()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->accesstoken().data(), static_cast<int>(this->accesstoken().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.AuthenticateREQ.accessToken"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string appId = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_appid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->appid().data(), static_cast<int>(this->appid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.AuthenticateREQ.appId"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ChatPb.AuthenticateREQ)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ChatPb.AuthenticateREQ)
  return false;
#undef DO_
}

void AuthenticateREQ::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ChatPb.AuthenticateREQ)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string openId = 1;
  if (this->openid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->openid().data(), static_cast<int>(this->openid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.AuthenticateREQ.openId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->openid(), output);
  }

  // string accessToken = 2;
  if (this->accesstoken().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accesstoken().data(), static_cast<int>(this->accesstoken().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.AuthenticateREQ.accessToken");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->accesstoken(), output);
  }

  // string appId = 3;
  if (this->appid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->appid().data(), static_cast<int>(this->appid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.AuthenticateREQ.appId");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->appid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ChatPb.AuthenticateREQ)
}

::google::protobuf::uint8* AuthenticateREQ::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ChatPb.AuthenticateREQ)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string openId = 1;
  if (this->openid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->openid().data(), static_cast<int>(this->openid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.AuthenticateREQ.openId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->openid(), target);
  }

  // string accessToken = 2;
  if (this->accesstoken().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->accesstoken().data(), static_cast<int>(this->accesstoken().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.AuthenticateREQ.accessToken");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->accesstoken(), target);
  }

  // string appId = 3;
  if (this->appid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->appid().data(), static_cast<int>(this->appid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.AuthenticateREQ.appId");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->appid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChatPb.AuthenticateREQ)
  return target;
}

size_t AuthenticateREQ::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChatPb.AuthenticateREQ)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string openId = 1;
  if (this->openid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->openid());
  }

  // string accessToken = 2;
  if (this->accesstoken().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->accesstoken());
  }

  // string appId = 3;
  if (this->appid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->appid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AuthenticateREQ::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ChatPb.AuthenticateREQ)
  GOOGLE_DCHECK_NE(&from, this);
  const AuthenticateREQ* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AuthenticateREQ>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ChatPb.AuthenticateREQ)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ChatPb.AuthenticateREQ)
    MergeFrom(*source);
  }
}

void AuthenticateREQ::MergeFrom(const AuthenticateREQ& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ChatPb.AuthenticateREQ)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.openid().size() > 0) {

    openid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.openid_);
  }
  if (from.accesstoken().size() > 0) {

    accesstoken_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accesstoken_);
  }
  if (from.appid().size() > 0) {

    appid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.appid_);
  }
}

void AuthenticateREQ::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ChatPb.AuthenticateREQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AuthenticateREQ::CopyFrom(const AuthenticateREQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChatPb.AuthenticateREQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthenticateREQ::IsInitialized() const {
  return true;
}

void AuthenticateREQ::Swap(AuthenticateREQ* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AuthenticateREQ::InternalSwap(AuthenticateREQ* other) {
  using std::swap;
  openid_.Swap(&other->openid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  accesstoken_.Swap(&other->accesstoken_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  appid_.Swap(&other->appid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AuthenticateREQ::GetMetadata() const {
  protobuf_chat_2eauthenticate_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2eauthenticate_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void AuthenticateRES::InitAsDefaultInstance() {
  ::ChatPb::_AuthenticateRES_default_instance_._instance.get_mutable()->user_ = const_cast< ::ChatPb::User*>(
      ::ChatPb::User::internal_default_instance());
}
void AuthenticateRES::clear_user() {
  if (GetArenaNoVirtual() == NULL && user_ != NULL) {
    delete user_;
  }
  user_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AuthenticateRES::kAuthorizedFieldNumber;
const int AuthenticateRES::kUserFieldNumber;
const int AuthenticateRES::kMessageFieldNumber;
const int AuthenticateRES::kCodeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AuthenticateRES::AuthenticateRES()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_chat_2eauthenticate_2eproto::scc_info_AuthenticateRES.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ChatPb.AuthenticateRES)
}
AuthenticateRES::AuthenticateRES(const AuthenticateRES& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.has_user()) {
    user_ = new ::ChatPb::User(*from.user_);
  } else {
    user_ = NULL;
  }
  ::memcpy(&authorized_, &from.authorized_,
    static_cast<size_t>(reinterpret_cast<char*>(&code_) -
    reinterpret_cast<char*>(&authorized_)) + sizeof(code_));
  // @@protoc_insertion_point(copy_constructor:ChatPb.AuthenticateRES)
}

void AuthenticateRES::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&user_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&code_) -
      reinterpret_cast<char*>(&user_)) + sizeof(code_));
}

AuthenticateRES::~AuthenticateRES() {
  // @@protoc_insertion_point(destructor:ChatPb.AuthenticateRES)
  SharedDtor();
}

void AuthenticateRES::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete user_;
}

void AuthenticateRES::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* AuthenticateRES::descriptor() {
  ::protobuf_chat_2eauthenticate_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2eauthenticate_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const AuthenticateRES& AuthenticateRES::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_chat_2eauthenticate_2eproto::scc_info_AuthenticateRES.base);
  return *internal_default_instance();
}


void AuthenticateRES::Clear() {
// @@protoc_insertion_point(message_clear_start:ChatPb.AuthenticateRES)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && user_ != NULL) {
    delete user_;
  }
  user_ = NULL;
  ::memset(&authorized_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&code_) -
      reinterpret_cast<char*>(&authorized_)) + sizeof(code_));
  _internal_metadata_.Clear();
}

bool AuthenticateRES::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ChatPb.AuthenticateRES)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bool authorized = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &authorized_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .ChatPb.User user = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_user()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ChatPb.AuthenticateRES.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .ChatPb.ErrorCode code = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_code(static_cast< ::ChatPb::ErrorCode >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ChatPb.AuthenticateRES)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ChatPb.AuthenticateRES)
  return false;
#undef DO_
}

void AuthenticateRES::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ChatPb.AuthenticateRES)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool authorized = 1;
  if (this->authorized() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(1, this->authorized(), output);
  }

  // .ChatPb.User user = 2;
  if (this->has_user()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_user(), output);
  }

  // string message = 3;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.AuthenticateRES.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->message(), output);
  }

  // .ChatPb.ErrorCode code = 4;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      4, this->code(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ChatPb.AuthenticateRES)
}

::google::protobuf::uint8* AuthenticateRES::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ChatPb.AuthenticateRES)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool authorized = 1;
  if (this->authorized() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(1, this->authorized(), target);
  }

  // .ChatPb.User user = 2;
  if (this->has_user()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_user(), deterministic, target);
  }

  // string message = 3;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ChatPb.AuthenticateRES.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->message(), target);
  }

  // .ChatPb.ErrorCode code = 4;
  if (this->code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      4, this->code(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChatPb.AuthenticateRES)
  return target;
}

size_t AuthenticateRES::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChatPb.AuthenticateRES)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string message = 3;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // .ChatPb.User user = 2;
  if (this->has_user()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *user_);
  }

  // bool authorized = 1;
  if (this->authorized() != 0) {
    total_size += 1 + 1;
  }

  // .ChatPb.ErrorCode code = 4;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AuthenticateRES::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ChatPb.AuthenticateRES)
  GOOGLE_DCHECK_NE(&from, this);
  const AuthenticateRES* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const AuthenticateRES>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ChatPb.AuthenticateRES)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ChatPb.AuthenticateRES)
    MergeFrom(*source);
  }
}

void AuthenticateRES::MergeFrom(const AuthenticateRES& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ChatPb.AuthenticateRES)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.has_user()) {
    mutable_user()->::ChatPb::User::MergeFrom(from.user());
  }
  if (from.authorized() != 0) {
    set_authorized(from.authorized());
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
}

void AuthenticateRES::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ChatPb.AuthenticateRES)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AuthenticateRES::CopyFrom(const AuthenticateRES& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChatPb.AuthenticateRES)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AuthenticateRES::IsInitialized() const {
  return true;
}

void AuthenticateRES::Swap(AuthenticateRES* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AuthenticateRES::InternalSwap(AuthenticateRES* other) {
  using std::swap;
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(user_, other->user_);
  swap(authorized_, other->authorized_);
  swap(code_, other->code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata AuthenticateRES::GetMetadata() const {
  protobuf_chat_2eauthenticate_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chat_2eauthenticate_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ChatPb
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ChatPb::AuthenticateREQ* Arena::CreateMaybeMessage< ::ChatPb::AuthenticateREQ >(Arena* arena) {
  return Arena::CreateInternal< ::ChatPb::AuthenticateREQ >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ChatPb::AuthenticateRES* Arena::CreateMaybeMessage< ::ChatPb::AuthenticateRES >(Arena* arena) {
  return Arena::CreateInternal< ::ChatPb::AuthenticateRES >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
